---

spring:
  profiles: in-memory
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: cloud
  datasource:
    url: jdbc:postgres://jwavdghpikkodc:45f4f050d808f7d044ca19d3e54977d454f62ed627dde7950491cf39e40f6432@ec2-174-129-33-14.compute-1.amazonaws.com:5432/dc2b4
    username: jwavdghpikkodc
    password: 45f4f050d808f7d044ca19d3e54977d454f62ed627dde7950491cf39e40f6432
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

---

spring:
  profiles: cloud
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
